import { useEffect, useMemo, useState } from "react";
import { num } from "@/lib/format";
import { Dice5, Loader2, RefreshCw, Users2, Coins, Trophy, TrendingUp, Zap } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import LIVE_CATALOG from "@/config/liveCatalogSeed.json";

/**
 * AdminIgaming — read-only monitoring for the 2J (iGaming) provider integration.
 *
 * Surfaces the launchable games catalog, the numeric player map (igaming_players)
 * and the seamless bet/win ledger (igaming_ledger). COMPLIANCE: this is monitoring
 * only — there is NO per-player odds control here. Profit is the certified house
 * edge over volume (GGR = stakes − payouts), shown for visibility, never a lever.
 *
 * Reads run as the logged-in admin (RLS: is_admin(auth.uid())); anon/regular
 * users cannot see this data.
 */

type Raw = { bet_amount?: number; win_amount?: number; game_name?: string; game_uid?: string; game_round?: string };
type Ledger = {
  id: string;
  user_id: string;
  tx_id: string;
  type: string;
  amount: number;
  balance_after: number;
  raw: Raw | null;
  created_at: string;
};

const fmt = (n: number) => num(n, { max: 2 });
const short = (id: string) => `${id.slice(0, 8)}…`;

const CARD = "rounded-2xl p-4 border border-white/10";

export default function AdminIgaming() {
  const [rows, setRows] = useState<Ledger[]>([]);
  const [playerCount, setPlayerCount] = useState(0);
  const [names, setNames] = useState<Record<string, string>>({});
  const [energyByTx, setEnergyByTx] = useState<Record<string, number>>({});
  const [energyTotals, setEnergyTotals] = useState({ wager: 0, mining: 0, total: 0 });
  const [loading, setLoading] = useState(true);

  const load = async () => {
    setLoading(true);
    const [{ data: ledger }, { count }] = await Promise.all([
      supabase
        .from("igaming_ledger")
        .select("id, user_id, tx_id, type, amount, balance_after, raw, created_at")
        .order("created_at", { ascending: false })
        .limit(200),
      supabase.from("igaming_players").select("player_id", { count: "exact", head: true }),
    ]);
    const list = (ledger || []) as Ledger[];
    setRows(list);
    setPlayerCount(count || 0);

    // C74 ecosystem energy generated by these 2J settlements (wager + mining),
    // keyed on the settlement tx_id. Admin can read energy_ledger via the
    // energy_ledger_admin_read policy; no secrets, monitoring only.
    const txIds = [...new Set(list.map((r) => r.tx_id).filter(Boolean))];
    const byTx: Record<string, number> = {};
    const totals = { wager: 0, mining: 0, total: 0 };
    if (txIds.length) {
      const { data: energy } = await supabase
        .from("energy_ledger")
        .select("delta, kind, reference")
        .in("reference", txIds)
        .in("kind", ["wager", "mining"]);
      for (const e of (energy || []) as { delta: number; kind: string; reference: string }[]) {
        const d = Number(e.delta) || 0;
        byTx[e.reference] = (byTx[e.reference] || 0) + d;
        totals.total += d;
        if (e.kind === "wager") totals.wager += d; else totals.mining += d;
      }
    }
    setEnergyByTx(byTx);
    setEnergyTotals(totals);

    const ids = [...new Set(list.map((r) => r.user_id))];
    if (ids.length) {
      const { data: profs } = await supabase.from("profiles").select("id, email, full_name").in("id", ids);
      const map: Record<string, string> = {};
      for (const p of (profs || []) as { id: string; email?: string; full_name?: string }[]) {
        map[p.id] = p.full_name || p.email || short(p.id);
      }
      setNames(map);
    }
    setLoading(false);
  };

  useEffect(() => { load(); /* eslint-disable-next-line react-hooks/exhaustive-deps */ }, []);

  const stats = useMemo(() => {
    let bet = 0, win = 0;
    const players = new Set<string>();
    for (const r of rows) {
      bet += Number(r.raw?.bet_amount ?? 0);
      win += Number(r.raw?.win_amount ?? 0);
      players.add(r.user_id);
    }
    return { bet, win, ggr: bet - win, activePlayers: players.size, rounds: rows.length };
  }, [rows]);

  const providers = useMemo(() => {
    const s = new Set((LIVE_CATALOG as { provider: string }[]).map((g) => g.provider));
    return [...s];
  }, []);

  return (
    <div className="space-y-5">
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div>
          <h1 className="text-2xl font-black text-white tracking-tight flex items-center gap-2">
            <Dice5 className="h-5 w-5 text-emerald-400" /> C7 Games
          </h1>
          <p className="text-xs text-white/50 mt-1">
            Live provider games, players &amp; seamless bet/win ledger — monitoring only.
          </p>
        </div>
        <button onClick={load} disabled={loading}
          className="inline-flex items-center gap-2 rounded-lg px-3 py-2 text-xs font-semibold text-white outline-none disabled:opacity-50"
          style={{ background: "#ffffff", border: "1px solid rgba(15,23,42,0.1)" }}>
          {loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <RefreshCw className="h-4 w-4" />} Refresh
        </button>
      </div>

      {/* Stat cards */}
      <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-7 gap-3">
        <div className={CARD} style={{ background: "rgba(16,185,129,0.10)" }}>
          <div className="flex items-center gap-2 text-emerald-300 text-xs font-bold"><Dice5 className="h-4 w-4" /> Games</div>
          <div className="text-2xl font-black text-white mt-1">{(LIVE_CATALOG as unknown[]).length}</div>
          <div className="text-[10px] text-white/40 mt-0.5">{providers.join(", ")} · launchable</div>
        </div>
        <div className={CARD} style={{ background: "rgba(59,130,246,0.10)" }}>
          <div className="flex items-center gap-2 text-blue-300 text-xs font-bold"><Users2 className="h-4 w-4" /> Players</div>
          <div className="text-2xl font-black text-white mt-1">{fmt(playerCount)}</div>
          <div className="text-[10px] text-white/40 mt-0.5">mapped to provider</div>
        </div>
        <div className={CARD} style={{ background: "rgba(99,102,241,0.10)" }}>
          <div className="flex items-center gap-2 text-indigo-300 text-xs font-bold"><TrendingUp className="h-4 w-4" /> Active</div>
          <div className="text-2xl font-black text-white mt-1">{fmt(stats.activePlayers)}</div>
          <div className="text-[10px] text-white/40 mt-0.5">in last {stats.rounds} events</div>
        </div>
        <div className={CARD} style={{ background: "rgba(245,158,11,0.10)" }}>
          <div className="flex items-center gap-2 text-amber-300 text-xs font-bold"><Coins className="h-4 w-4" /> Stakes</div>
          <div className="text-2xl font-black text-white mt-1">{fmt(stats.bet)}</div>
          <div className="text-[10px] text-white/40 mt-0.5">recent bet volume</div>
        </div>
        <div className={CARD} style={{ background: "rgba(244,63,94,0.10)" }}>
          <div className="flex items-center gap-2 text-rose-300 text-xs font-bold"><Trophy className="h-4 w-4" /> Payouts</div>
          <div className="text-2xl font-black text-white mt-1">{fmt(stats.win)}</div>
          <div className="text-[10px] text-white/40 mt-0.5">recent win volume</div>
        </div>
        <div className={CARD} style={{ background: stats.ggr >= 0 ? "rgba(16,185,129,0.14)" : "rgba(244,63,94,0.14)" }}>
          <div className="flex items-center gap-2 text-white/80 text-xs font-bold"><TrendingUp className="h-4 w-4" /> GGR (net)</div>
          <div className={`text-2xl font-black mt-1 ${stats.ggr >= 0 ? "text-emerald-300" : "text-rose-300"}`}>{fmt(stats.ggr)}</div>
          <div className="text-[10px] text-white/40 mt-0.5">stakes − payouts (house)</div>
        </div>
        <div className={CARD} style={{ background: "rgba(250,204,21,0.12)" }}>
          <div className="flex items-center gap-2 text-yellow-300 text-xs font-bold"><Zap className="h-4 w-4" /> C74 Energy</div>
          <div className="text-2xl font-black text-white mt-1">{fmt(energyTotals.total)}</div>
          <div className="text-[10px] text-white/40 mt-0.5">wager {fmt(energyTotals.wager)} · mining {fmt(energyTotals.mining)}</div>
        </div>
      </div>

      {/* Recent activity */}
      <div className="rounded-2xl border border-white/10 overflow-hidden" style={{ background: "#ffffff" }}>
        <div className="px-4 py-3 border-b border-white/10 text-sm font-bold text-white">Recent bet / win activity</div>
        {loading ? (
          <div className="p-8 text-center text-white/50"><Loader2 className="h-5 w-5 animate-spin inline" /></div>
        ) : rows.length === 0 ? (
          <div className="p-8 text-center text-white/40 text-sm">No game activity yet. Bets and wins will appear here as players play the games.</div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-xs">
              <thead>
                <tr className="text-white/40 text-left">
                  <th className="px-4 py-2 font-semibold">Time</th>
                  <th className="px-4 py-2 font-semibold">Player</th>
                  <th className="px-4 py-2 font-semibold">Game</th>
                  <th className="px-4 py-2 font-semibold text-right">Bet</th>
                  <th className="px-4 py-2 font-semibold text-right">Win</th>
                  <th className="px-4 py-2 font-semibold text-right">Net</th>
                  <th className="px-4 py-2 font-semibold text-right">C74 ⚡</th>
                  <th className="px-4 py-2 font-semibold text-right">Balance</th>
                </tr>
              </thead>
              <tbody>
                {rows.map((r) => {
                  const bet = Number(r.raw?.bet_amount ?? 0);
                  const win = Number(r.raw?.win_amount ?? 0);
                  const net = win - bet;
                  return (
                    <tr key={r.id} className="border-t border-white/5 text-white/80">
                      <td className="px-4 py-2 whitespace-nowrap text-white/50">{new Date(r.created_at).toLocaleString()}</td>
                      <td className="px-4 py-2 whitespace-nowrap">{names[r.user_id] || short(r.user_id)}</td>
                      <td className="px-4 py-2 whitespace-nowrap">{r.raw?.game_name || r.raw?.game_uid || "—"}</td>
                      <td className="px-4 py-2 text-right tabular-nums">{bet ? fmt(bet) : "—"}</td>
                      <td className="px-4 py-2 text-right tabular-nums text-emerald-300">{win ? fmt(win) : "—"}</td>
                      <td className={`px-4 py-2 text-right tabular-nums font-semibold ${net >= 0 ? "text-emerald-300" : "text-rose-300"}`}>{net >= 0 ? "+" : ""}{fmt(net)}</td>
                      <td className="px-4 py-2 text-right tabular-nums text-yellow-300">{energyByTx[r.tx_id] ? `+${fmt(energyByTx[r.tx_id])}` : "—"}</td>
                      <td className="px-4 py-2 text-right tabular-nums text-white/60">{fmt(r.balance_after)}</td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </div>

      <p className="text-[10px] text-white/30 leading-relaxed">
        Compliance: monitoring only. Outcomes are the certified game RTP; there is no per-player result control.
        GGR shown is the certified house edge realised over volume (stakes − payouts).
      </p>
    </div>
  );
}
